# Generated by Django 5.0 on 2023-12-14 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, verbose_name='Nombre del tipo de habitacion')),
                ('detail', models.TextField(verbose_name='Detalle del tipo')),
            ],
            options={
                'verbose_name': 'Room type',
                'verbose_name_plural': 'Room types',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.SmallIntegerField()),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Piso de la habitacion')),
                ('night_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de la habitacion')),
                ('description', models.TextField(verbose_name='Descripcion de la habitacion')),
                ('state', models.CharField(choices=[('libre', 'sin huesped'), ('ocupada', 'con huesped'), ('rentada', 'pagada pero sin huesped'), ('no', 'no disponible')], max_length=50)),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room_type', verbose_name='Tipo habitacion')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
